#!/bin/bash
# Title: HVA - HTML Video Automator
# Author: Loïc Cattani "arko" <loic.cattani@gmail.com>
# Begin: 2011.01.28
#
# Ce script automatise l'encodage et la préparation du code HTML pour
# une ou plusieurs vidéos déposées dans une boîte de dépôt.
#
# Il est prévu pour être executé automatiquement par launchd lorsque
# la boîte de dépôt est modifiée.

# Config files
config_file="hva.conf"
prod_config_file="/etc/hva.conf"

# Load config file and set environment
if [[ -e $config_file ]]; then
  env="dev"
elif [[ -e $prod_config_file ]]; then
  config_file=$prod_config_file
  env="prod"
else
  echo "Can't find config file! Exiting..."
  exit 1
fi
source $config_file
# Keep in mind this is not secure. As one may add nasty code in
# config file! It should only be writable by owner.

# Log messages to log file
function log () {
  echo "$(date) - $1" >> $log_file
}

log "HTML Video Automator started"

# Lock HVA execution (MUTEX)
mkdir /tmp/hva-lock 2> /dev/null
if [[ $? != 0 ]]; then
  log "HVA already running. Exiting..."
  exit 0
fi

# Get all files in launchpad (Assumed they are all video files)
# If not, we'll see what happens... ffmpeg can read nearly everything
files=($(find $launchpad/*))

log "${#files[@]} files found in $launchpad"

for file in ${files[@]}; do
  
  # Getting filename without extension
  file_basename=$(basename $file)
  file_name=${file_basename%.*}
  
  log "Processing $file_basename"
  
  #Encoding H.264 mp4
  outfile="${file_name}.mp4"
  log "Encoding $file to mp4"
  start_time=$(date +%s)
  ffmpeg -y -i $file -threads 8 -f mp4 -vcodec libx264 -vpre slow -vpre ipod640 -b 1200k -acodec libfaac -ab 160000 -ac 2 -s 640x480 $payload/$outfile 2>> $ffmpeg_log_file
  exit_code=$?
  elapsed="$(expr $(date +%s) - $start_time)"
  if [[ $exit_code > 0 ]]; then
    log "ERROR encoding $outfile. Elapsed $elapsed seconds"
  else
    log "SUCCESS encoding $outfile. Elapsed $elapsed seconds"
  fi
  
  #Encoding VP8 webm
  outfile="${file_name}.webm"
  log "Encoding $file to webm"
  start_time=$(date +%s)
  ffmpeg -y -i $file -threads 8 -f webm -vcodec libvpx -g 120 -level 216 -qmax 50 -qmin 10 -rc_buf_aggressivity 0.95 -b 1200k -acodec libvorbis -aq 80 -ac 2 -s 640x480 $payload/$outfile 2>> $ffmpeg_log_file
  exit_code=$?
  elapsed="$(expr $(date +%s) - $start_time)"
  if [[ $exit_code > 0 ]]; then
    log "ERROR encoding $outfile. Elapsed $elapsed seconds"
  else
    log "SUCCESS encoding $outfile. Elapsed $elapsed seconds"
  fi
  
  # TODO:
  # Build HTML document
  # scp encoded movies and html doc to www server
  # scp source movies to archive server
  # Clean local files
  
done

log "Done."

# Unlock
rm -r /tmp/hva-lock

exit 0
